---
- name: user module
  hosts: rhel
  tasks: 
    - name: user {{ myuser }} creation
      ansible.builtin.user:
        name: "{{ myuser }}"
        comment: "{{ comment }}"
        group: wheel
        state: present

    - name: Display Username Entered
      ansible.builtin.debug:
        msg: "The username is: {{ myuser }}"

      
