---
- name: user module
  hosts: rhel
  tasks: 
    - name: user {{ myuser }} creation
      ansible.builtin.user:
        name: "{{ myuser }}"
        comment: "{{ comment }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"
