---
- name: user module
  hosts: all
  tasks: 
    - name: user {{ myuser }} creation
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{{ mypassword | password_hash('sha512') }}"

    - name: Display Username Entered
      ansible.builtin.debug:
        msg: "The username is: {{ myuser }}"

    - name: Display default Password
      ansible.builtin.debug:
        msg: "Password: {{ mypassword }}"
