---
- name: update widnows OS
  hosts: all
  tasks:
    - name: Install all security updates with automatic reboots
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        reboot: yes
