---
- name: Create User Password
  hosts: all
  tasks:
    - name: Set password for user {{ myuser }} 
      ansible.windows.win_user:
        name: "{{ myuser }}"
        password: "{{ mypassword }}"

