---
- name: Password Policy
  hosts: all
  tasks:
    - name: Ensure Enforce password history
      community.windows.win_security_policy:
        sction: System Access
        key: PasswordHistorySize
        value: "{{ max_passwords_saved }}"
